# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bikebuddyapi:
    image: bikebuddyapi
    build:
      context: .
      dockerfile: bikebuddy.api/Dockerfile
    ports:
      - 8080:4040

  bikebuddyweb:
    image: bikebuddyapp
    build:
      context: .
      dockerfile: bikebuddy.app/Dockerfile
    ports:
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:8080
      # - ASPNETCORE_HTTPS_PORT=443
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - bikebuddyapi
