name: Deploy to Azure Container App

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_APP_NAME: bikebuddy-apps
  AZURE_CONTAINER_REGISTRY: bbreg.azurecr.io
  AZURE_RESOURCE_GROUP: BikeBuddy
  AZURE_ACR_ENVIRONMENT: managedEnvironment-BikeBuddy-ba12
  API_IMAGE_NAME: bikebuddyapi
  WEB_IMAGE_NAME: bikebuddyapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: bbreg
        password: ${{ secrets.AZURE_ACR_ADMIN }}

    - name: Build and push API Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./bikebuddy.api/Dockerfile
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest

    - name: Build and push Web Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./bikebuddy.app/Dockerfile
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.WEB_IMAGE_NAME }}:latest

    - name: Deploy API to Azure Container App
      run: |
        az containerapp create --name ${{ env.API_IMAGE_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --registry-server ${{ env.AZURE_CONTAINER_REGISTRY }} --environment ${{ env.AZURE_ACR_ENVIRONMENT }} --registry-username bbreg --registry-password ${{ secrets.AZURE_ACR_ADMIN }} --image bbreg.azurecr.io/${{ env.API_IMAGE_NAME }}:latest

    - name: Deploy Web to Azure Container App
      run: |
        az containerapp create --name ${{ env.WEB_IMAGE_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --registry-server ${{ env.AZURE_CONTAINER_REGISTRY }} --environment ${{ env.AZURE_ACR_ENVIRONMENT }} --registry-username bbreg --registry-password ${{ secrets.AZURE_ACR_ADMIN }} --image bbreg.azurecr.io/${{ env.WEB_IMAGE_NAME }}:latest
